/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RAVEN;


import POJO.F_SanPham;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ha
 */
public class dsSanPham extends javax.swing.JPanel {

    /**
     * Creates new form dsSanPham
     */
    DefaultTableModel dtm = new  DefaultTableModel();
    public dsSanPham() {
        initComponents();
        String [] tieuDe ={"Mã SP","Tên SP","Loại SP","Số lượng","Đơn giá"};
        dtm.setColumnIdentifiers(tieuDe);
        table_dsSP.setModel(dtm);
        HienThi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_dsSP = new javax.swing.JTable();

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        table_dsSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP ", "Loại SP", "Số lượng ", "Đơn giá"
            }
        ));
        jScrollPane3.setViewportView(table_dsSP);

        jLayeredPane3.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane3)
        );
    }// </editor-fold>//GEN-END:initComponents
  private void HienThi() {
        ArrayList<F_SanPham> dsSP = DAO.DAO_SanPham.layDanhSachSanPham();
        dtm.setRowCount(0);
        for(F_SanPham sp: dsSP)
        {
            Vector<Object> v = new Vector<Object>();
            v.add(sp.getMaSP());
            v.add(sp.getTenSP());
            v.add(sp.getTenLoai());
            v.add(sp.getSoLuong());
            v.add(sp.getDonGia());
            dtm.addRow(v);
        }
        table_dsSP.setModel(dtm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table_dsSP;
    // End of variables declaration//GEN-END:variables
}
